version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.10.1-ce.0
    container_name: gitlab
    restart: always
    # hostname: 'gitlab.example.com'
    # environment:
    # GITLAB_OMNIBUS_CONFIG: |
    #   # Add any other gitlab.rb configuration here, each on its own line
    #   external_url 'https://gitlab.example.com'
    ports:
      - '8080:80'
      - '4443:443'
      - '222:22'
    volumes:
      - '/home/andreav/docker/gitlab/gitlab-ce/config:/etc/gitlab'
      - '/home/andreav/docker/gitlab/gitlab-ce/logs:/var/log/gitlab'
      - '/home/andreav/docker/gitlab/gitlab-ce/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './gitlab-ce/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab
networks:
  gitlab:
    name: gitlab-network
